# Generated by Django 4.2.6 on 2023-11-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_message_faculty_message_media_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='comment',
            field=models.TextField(max_length=500, verbose_name='Поздравление'),
        ),
    ]
